id: returnamber36996.sunTimes1
version: 1

dashboard:
  states:
    - label: '{{daylightPercentage.value}} {{daylightPercentage.unit}}'
      alternatives: null
  actions: []
  basicPlus: []

detailView:
  - label: 'Daytime'
    displayType: state
    state:
      label: '{{daytime.value}}'
      unit: daytime.unit

  - label: 'Daylight Percentage'
    displayType: slider
    slider:
      range:
        - 0
        - 100
      step: 1
      valueType: number
      value: daylightPercentage.value
      unit: daylightPercentage.unit
    state: null

automation:
  conditions:
    - label: 'Daytime (hh:mm:ss)'
      displayType: textField
      textField:
        value: daytime.value
        valueType: string
        unit: daytime.unit

    - label: 'Daylight Percentage'
      displayType: numberField
      numberField:
        value: daylightPercentage.value
        valueType: number
        unit: daylightPercentage.unit

  actions: []
